{{- if .Values.emqx.persistence.emqx_data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    katenary.v3/compose-hash: 02957997c43d550dc2189d830877b3934db1507a
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
    katenary.v3/component: emqx
  name: '{{ include "deploy.fullname" . }}-emqx-emqx-data'
spec:
  accessModes:
  {{- .Values.emqx.persistence.emqx_data.accessMode | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ tpl .Values.emqx.persistence.emqx_data.size $ }}
  {{- if ne .Values.emqx.persistence.emqx_data.storageClass "-" }}
  storageClassName: '{{ .Values.emqx.persistence.emqx_data.storageClass }}'
  {{- end }}

{{- end }}