apiVersion: v1
data:
  BOTS_PATH: /Users/jbid/Documents/deploy
  BROKER_HOST: emqx
  BROKER_PORT: "1883"
  CONFIG_PASSWORD: a
  PASSWORD: admin
  USERNAME: admin
kind: ConfigMap
metadata:
  annotations:
    katenary.v3/compose-hash: 02957997c43d550dc2189d830877b3934db1507a
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
    katenary.v3/component: backend-api
  name: '{{ include "deploy.fullname" . }}-backend-api'
